version: "3.7"

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    networks:
      - web-net
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/down:/usr/share/down
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - fastapi
    environment:
      - TZ=Asia/Taipei
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    networks:
      - web-net
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Taipei
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"

  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    restart: always
    volumes:
      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mariadb/dump:/docker-entrypoint-initdb.d
    networks:
      - db-net
    ports:
      - 3306:3306
    healthcheck:
      test: "exit 0"
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=@wu18au
      - MYSQL_USER=tibame
      - MYSQL_PASSWORD=@wu18au
      - MYSQL_DATABASE=my_db

  mongodb:
    image: mongo
    container_name: myMGO
    hostname: myMGO
    restart: always
    volumes:
      - ./mongodb:/data/db
    networks:
      - db-net
    ports:
      - 17017:27017
    environment:
      - TZ=Asia/Taipei
      - MONGO_INITDB_ROOT_USERNAME=tibame
      - MONGO_INITDB_ROOT_PASSWORD=@wu18au

  fastapi:
    build: fastapi
    image: myfastapi
    container_name: fastapi
    hostname: fastapi
    volumes:
      - ./fastapi/myapp:/app
    environment:
      - MONGO_DETAILS=mongodb://tibame:^%%40wu18au@mongodb:27017
      - DATABASE_URL=mysql+pymysql://tibame:%40wu18au@mariadb:3306/my_db
      - PORT=8080
      - TZ=Asia/Taipei
    depends_on:
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - db-net
      - web-net
    ports:
      - 8080:8080

networks:
  db-net:
    driver: bridge
  web-net:
    driver: bridge
